server:
  port: 8001          #端口
spring:
  application:
    name: provider
  datasource:           #数据源
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    type: com.alibaba.druid.pool.DruidDataSource    #druid连接池
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true      # 开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    lease-expiration-duration-in-seconds: 30   # 续约更新时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 10   # 续约到期时间（默认90秒）
